/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh auth token */
    post: operations['refresh-token'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a refresh token */
    post: operations['revoke-token'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in */
    post: operations['sign-in'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign up */
    post: operations['sign-up'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify user email to finish creating account */
    post: operations['verify-email'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify/resend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend email verification email */
    post: operations['resend-email-verification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/debug/newsletters/{newsletterId}/send': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Immediately queue a newsletter to send - for debugging */
    post: operations['force-send-newsletter'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Downloads all newsletters in json format */
    get: operations['export-newsletters'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/export/{newsletterId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Downloads a single newsletter in JSON format */
    get: operations['export-newsletter'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/feed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Gets data about an RSS feed URL */
    post: operations['get-feed-metadata'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/issues': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all issues for a user */
    get: operations['get-issues'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/issues/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single issue with all items */
    get: operations['get-issue'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/link/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Redirect to a newsletter item after marking an item as read */
    get: operations['link-track'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletter/{newsletterId}/feed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all feeds included in a newsletter */
    get: operations['list-feeds'];
    put?: never;
    /** Add a feed to a newsletter */
    post: operations['add-feed'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletter/{newsletterId}/feed/{feedId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get data associated with a feed */
    get: operations['get-feed'];
    /** Update the name and URL of a feed */
    put: operations['update-feed'];
    post?: never;
    /** Deletes a feed from a newsletter */
    delete: operations['delete-feed'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletter/{newsletterId}/feed/{feedId}/filter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add a filter to a newsletter feed */
    post: operations['add-feed-filter'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletter/{newsletterId}/feed/{feedId}/filter/{filterId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Update a filter to a newsletter feed */
    post: operations['update-feed-filter'];
    /** Delete a filter on a newsletter feed */
    delete: operations['delete-feed-filter'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletter/{newsletterId}/feed/{feedId}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Preview how filters impact the items in the feed */
    get: operations['preview-feed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletter/{newsletterId}/one-off': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Schedule the newsletter to send at a future date off schedule */
    post: operations['schedule-one-off'];
    /** @description Cancel an upcoming one off */
    delete: operations['cancel-one-off'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletter/{newsletterId}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Change the status of a newsletter to active or inactive */
    patch: operations['update-newsletter-status'];
    trace?: never;
  };
  '/newsletters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all newsletters */
    get: operations['list-newsletters'];
    put?: never;
    /** Create a new newsletter */
    post: operations['create-newsletter'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/newsletters/{newsletterId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single newsletter */
    get: operations['get-newsletter'];
    /** Update a single newsletter */
    put: operations['update-newsletter'];
    post?: never;
    /** Delete a newsletter and all of its feeds */
    delete: operations['delete-newsletter'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scheduler/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Runs the scheduler immediately - for debugging */
    post: operations['run-scheduler'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/unsubscribe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['unsubscribe'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get's the user's account data */
    get: operations['get-user'];
    put?: never;
    post?: never;
    /** Delete this user and all of their data */
    delete: operations['delete-user'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user's email */
    patch: operations['update-email'];
    trace?: never;
  };
  '/user/email/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify new email */
    post: operations['verify-email-update'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user's password */
    patch: operations['update-password'];
    trace?: never;
  };
  '/user/verify/resend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend email verification email for email update flow */
    post: operations['resend-email-verification-for-update'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AuthInputBody.json
       */
      readonly $schema?: string;
      /** @description Must be a valid email */
      email: string;
      password: string;
    };
    AuthOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AuthOutputBody.json
       */
      readonly $schema?: string;
      verified: boolean;
    };
    'Delete-userRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Delete-userRequest.json
       */
      readonly $schema?: string;
      password: string;
    };
    DetailedIssue: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/DetailedIssue.json
       */
      readonly $schema?: string;
      feeds: components['schemas']['IssueFeed'][] | null;
      issueId: string;
      newsletterId: string;
      newsletterName: string;
      /** Format: date-time */
      sentAt: string;
    };
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string;
      /** @description Error message text */
      message?: string;
      /** @description The value at the given location */
      value?: unknown;
    };
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ErrorModel.json
       */
      readonly $schema?: string;
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string;
      /** @description Optional list of individual error details */
      errors?: components['schemas']['ErrorDetail'][] | null;
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string;
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string;
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string;
    };
    ExistingRecievedFeed: {
      alias: string;
      newsletterName: string;
    };
    FeedFilter: {
      field: string;
      id: string;
      operator: string;
      pattern: string;
    };
    FeedMetaData: {
      Description: string;
      HtmlURL: string;
      Id: string;
      Title: string;
      URL: string;
    };
    'Get-feed-metadataRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Get-feed-metadataRequest.json
       */
      readonly $schema?: string;
      url: string;
    };
    GetFeedMetaDataOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/GetFeedMetaDataOutputBody.json
       */
      readonly $schema?: string;
      existingRecievedFeeds:
        | components['schemas']['ExistingRecievedFeed'][]
        | null;
      metadata: components['schemas']['FeedMetaData'];
    };
    Issue: {
      issueId: string;
      newsletterId: string;
      newsletterName: string;
      /** Format: date-time */
      sentAt: string;
    };
    IssueFeed: {
      items: components['schemas']['IssueItem'][] | null;
      title: string;
      webUrl: string;
    };
    IssueItem: {
      itemId: string;
      /** Format: date-time */
      publishDate: string;
      state: string;
      title: string;
      token: string;
    };
    ItemPreview: {
      id: string;
      matchedFilter?: components['schemas']['FeedFilter'];
      title: string;
      url: string;
    };
    Newsletter: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Newsletter.json
       */
      readonly $schema?: string;
      /** Format: date-time */
      createdAt: string;
      frequency: string;
      id: string;
      /** Format: date-time */
      lastSentAt?: string;
      name: string;
      /** Format: date-time */
      nextSendTime: string;
      /** Format: date-time */
      oneOffSendTime?: string;
      /** Format: date-time */
      regularSendTime?: string;
      /** Format: int64 */
      sendDay: number;
      /** Format: int64 */
      sendHour: number;
      /** Format: int64 */
      sendMinute: number;
      sendTimezone: string;
      status: string;
      /** Format: date-time */
      updatedAt: string;
    };
    OneOffSendInput: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OneOffSendInput.json
       */
      readonly $schema?: string;
      sendTime: string;
    };
    'Resend-email-verificationRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Resend-email-verificationRequest.json
       */
      readonly $schema?: string;
      email: string;
    };
    SubmittableFeedFields: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SubmittableFeedFields.json
       */
      readonly $schema?: string;
      alias: string;
      url: string;
    };
    SubmittableFeedFilterFields: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SubmittableFeedFilterFields.json
       */
      readonly $schema?: string;
      field: string;
      operator: string;
      pattern: string;
    };
    SubmittableNewsletterFields: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SubmittableNewsletterFields.json
       */
      readonly $schema?: string;
      /** @enum {string} */
      frequency: 'daily' | 'weekly' | 'monthly';
      name: string;
      /** Format: int64 */
      sendDay?: number;
      /** Format: int64 */
      sendHour: number;
      /** Format: int64 */
      sendMinute: number;
      sendTimezone: string;
    };
    UiDetailedFeed: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UiDetailedFeed.json
       */
      readonly $schema?: string;
      alias: string;
      description: string;
      filters: components['schemas']['FeedFilter'][] | null;
      htmlUrl: string;
      id: string;
      title: string;
      url: string;
    };
    UiFeed: {
      alias: string;
      description: string;
      htmlUrl: string;
      id: string;
      title: string;
      url: string;
    };
    UpdatableFeedFields: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UpdatableFeedFields.json
       */
      readonly $schema?: string;
      alias: string;
    };
    'Update-emailRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Update-emailRequest.json
       */
      readonly $schema?: string;
      email: string;
    };
    'Update-newsletter-statusRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Update-newsletter-statusRequest.json
       */
      readonly $schema?: string;
      /** @enum {string} */
      status: 'active' | 'inactive';
    };
    'Update-passwordRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Update-passwordRequest.json
       */
      readonly $schema?: string;
      currentPassword: string;
      newPassword: string;
    };
    'Verify-email-updateRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Verify-email-updateRequest.json
       */
      readonly $schema?: string;
      code: string;
    };
    'Verify-emailRequest': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Verify-emailRequest.json
       */
      readonly $schema?: string;
      code: string;
      email: string;
    };
    VisibleUser: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/VisibleUser.json
       */
      readonly $schema?: string;
      email: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthOutputBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'revoke-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthOutputBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AuthInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthOutputBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'sign-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AuthInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthOutputBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Verify-emailRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthOutputBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'resend-email-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Resend-email-verificationRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'force-send-newsletter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'export-newsletters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'export-newsletter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'get-feed-metadata': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Get-feed-metadataRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetFeedMetaDataOutputBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'get-issues': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Issue'][] | null;
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'get-issue': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DetailedIssue'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'link-track': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Temporary Redirect */
      307: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'list-feeds': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UiFeed'][] | null;
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'add-feed': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmittableFeedFields'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'get-feed': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
        feedId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UiDetailedFeed'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'update-feed': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
        feedId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatableFeedFields'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'delete-feed': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
        feedId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'add-feed-filter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
        feedId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmittableFeedFilterFields'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'update-feed-filter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
        feedId: string;
        filterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmittableFeedFilterFields'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'delete-feed-filter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
        feedId: string;
        filterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'preview-feed': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
        feedId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemPreview'][] | null;
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'schedule-one-off': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OneOffSendInput'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'cancel-one-off': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'update-newsletter-status': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Update-newsletter-statusRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'list-newsletters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Newsletter'][] | null;
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'create-newsletter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmittableNewsletterFields'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'get-newsletter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Newsletter'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'update-newsletter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmittableNewsletterFields'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'delete-newsletter': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        newsletterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'run-scheduler': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  unsubscribe: {
    parameters: {
      query?: {
        unsubscribeToken?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'get-user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VisibleUser'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'delete-user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Delete-userRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'update-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Update-emailRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'verify-email-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Verify-email-updateRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'update-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Update-passwordRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'resend-email-verification-for-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
}
