// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForSaveFeedItemDetails implements pgx.CopyFromSource.
type iteratorForSaveFeedItemDetails struct {
	rows                 []SaveFeedItemDetailsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveFeedItemDetails) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveFeedItemDetails) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FeedID,
		r.rows[0].Title,
		r.rows[0].Url,
		r.rows[0].PublishDate,
		r.rows[0].RetrievedAt,
	}, nil
}

func (r iteratorForSaveFeedItemDetails) Err() error {
	return nil
}

func (q *Queries) SaveFeedItemDetails(ctx context.Context, arg []SaveFeedItemDetailsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"feed_item"}, []string{"feed_id", "title", "url", "publish_date", "retrieved_at"}, &iteratorForSaveFeedItemDetails{rows: arg})
}

// iteratorForSaveFeedUrls implements pgx.CopyFromSource.
type iteratorForSaveFeedUrls struct {
	rows                 []SaveFeedUrlsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveFeedUrls) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveFeedUrls) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FeedID,
		r.rows[0].Url,
		r.rows[0].Source,
	}, nil
}

func (r iteratorForSaveFeedUrls) Err() error {
	return nil
}

func (q *Queries) SaveFeedUrls(ctx context.Context, arg []SaveFeedUrlsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"feed_url"}, []string{"feed_id", "url", "source"}, &iteratorForSaveFeedUrls{rows: arg})
}
