// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_filters.sql

package db

import (
	"context"
)

const addFeedFilter = `-- name: AddFeedFilter :exec
INSERT INTO newsletter_feed_filter (newsletter_feed_id, user_id, field, operator, pattern)
VALUES ($1, $2, $3, $4, $5)
`

type AddFeedFilterParams struct {
	NewsletterFeedID string
	UserID           string
	Field            FilterField
	Operator         FilterOperator
	Pattern          string
}

func (q *Queries) AddFeedFilter(ctx context.Context, arg AddFeedFilterParams) error {
	_, err := q.db.Exec(ctx, addFeedFilter,
		arg.NewsletterFeedID,
		arg.UserID,
		arg.Field,
		arg.Operator,
		arg.Pattern,
	)
	return err
}

const deleteFeedFilter = `-- name: DeleteFeedFilter :exec
DELETE FROM newsletter_feed_filter WHERE id = $1 AND user_id = $2
`

type DeleteFeedFilterParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteFeedFilter(ctx context.Context, arg DeleteFeedFilterParams) error {
	_, err := q.db.Exec(ctx, deleteFeedFilter, arg.ID, arg.UserID)
	return err
}

const deleteFeedFiltersForUser = `-- name: DeleteFeedFiltersForUser :exec
DELETE FROM newsletter_feed_filter WHERE user_id = $1
`

func (q *Queries) DeleteFeedFiltersForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteFeedFiltersForUser, userID)
	return err
}

const doesFilterExist = `-- name: DoesFilterExist :one
SELECT EXISTS(
    SELECT 1 FROM newsletter_feed_filter AS fil
    INNER JOIN newsletter_feed AS nlf ON fil.newsletter_feed_id = nlf.id
    WHERE fil.id = $3 AND fil.user_id = $1 AND nlf.newsletter_id = $2 AND nlf.id = $4
)
`

type DoesFilterExistParams struct {
	UserID           string
	NewsletterID     string
	FilterID         string
	NewsletterFeedID string
}

func (q *Queries) DoesFilterExist(ctx context.Context, arg DoesFilterExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, doesFilterExist,
		arg.UserID,
		arg.NewsletterID,
		arg.FilterID,
		arg.NewsletterFeedID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFiltersForFeed = `-- name: GetFiltersForFeed :many
SELECT id, field, operator, pattern FROM newsletter_feed_filter
WHERE user_id = $1 AND newsletter_feed_id = $2
`

type GetFiltersForFeedParams struct {
	UserID           string
	NewsletterFeedID string
}

type GetFiltersForFeedRow struct {
	ID       string
	Field    FilterField
	Operator FilterOperator
	Pattern  string
}

func (q *Queries) GetFiltersForFeed(ctx context.Context, arg GetFiltersForFeedParams) ([]GetFiltersForFeedRow, error) {
	rows, err := q.db.Query(ctx, getFiltersForFeed, arg.UserID, arg.NewsletterFeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFiltersForFeedRow
	for rows.Next() {
		var i GetFiltersForFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Field,
			&i.Operator,
			&i.Pattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFiltersForManyFeeds = `-- name: GetFiltersForManyFeeds :many
SELECT id, field, operator, pattern, newsletter_feed_id FROM newsletter_feed_filter
WHERE user_id = $1 AND newsletter_feed_id = ANY($2::UUID[])
`

type GetFiltersForManyFeedsParams struct {
	UserID  string
	FeedIds []string
}

type GetFiltersForManyFeedsRow struct {
	ID               string
	Field            FilterField
	Operator         FilterOperator
	Pattern          string
	NewsletterFeedID string
}

func (q *Queries) GetFiltersForManyFeeds(ctx context.Context, arg GetFiltersForManyFeedsParams) ([]GetFiltersForManyFeedsRow, error) {
	rows, err := q.db.Query(ctx, getFiltersForManyFeeds, arg.UserID, arg.FeedIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFiltersForManyFeedsRow
	for rows.Next() {
		var i GetFiltersForManyFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Field,
			&i.Operator,
			&i.Pattern,
			&i.NewsletterFeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedFilter = `-- name: UpdateFeedFilter :exec
UPDATE newsletter_feed_filter 
SET field = $1, operator = $2, pattern = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateFeedFilterParams struct {
	Field    FilterField
	Operator FilterOperator
	Pattern  string
	ID       string
}

func (q *Queries) UpdateFeedFilter(ctx context.Context, arg UpdateFeedFilterParams) error {
	_, err := q.db.Exec(ctx, updateFeedFilter,
		arg.Field,
		arg.Operator,
		arg.Pattern,
		arg.ID,
	)
	return err
}
