// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package db

import (
	"context"
)

const addFeed = `-- name: AddFeed :exec
INSERT INTO feed (name, url, newsletter_id)
VALUES ($1, $2, $3)
`

type AddFeedParams struct {
	Name         string
	Url          string
	NewsletterID string
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) error {
	_, err := q.db.Exec(ctx, addFeed, arg.Name, arg.Url, arg.NewsletterID)
	return err
}

const getFeedsForNewsletter = `-- name: GetFeedsForNewsletter :many
SELECT id, newsletter_id, name, url, last_retrieved_at, created_at, updated_at FROM feed WHERE newsletter_id = $1
`

func (q *Queries) GetFeedsForNewsletter(ctx context.Context, newsletterID string) ([]Feed, error) {
	rows, err := q.db.Query(ctx, getFeedsForNewsletter, newsletterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.NewsletterID,
			&i.Name,
			&i.Url,
			&i.LastRetrievedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
