// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type FeedUrlSource string

const (
	FeedUrlSourceCanonical      FeedUrlSource = "canonical"
	FeedUrlSourceUserSubmitted  FeedUrlSource = "user_submitted"
	FeedUrlSourceInFeedResponse FeedUrlSource = "in_feed_response"
	FeedUrlSourceUnknown        FeedUrlSource = "unknown"
)

func (e *FeedUrlSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedUrlSource(s)
	case string:
		*e = FeedUrlSource(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedUrlSource: %T", src)
	}
	return nil
}

type NullFeedUrlSource struct {
	FeedUrlSource FeedUrlSource
	Valid         bool // Valid is true if FeedUrlSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedUrlSource) Scan(value interface{}) error {
	if value == nil {
		ns.FeedUrlSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedUrlSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedUrlSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedUrlSource), nil
}

type FilterField string

const (
	FilterFieldTitle FilterField = "title"
	FilterFieldUrl   FilterField = "url"
)

func (e *FilterField) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FilterField(s)
	case string:
		*e = FilterField(s)
	default:
		return fmt.Errorf("unsupported scan type for FilterField: %T", src)
	}
	return nil
}

type NullFilterField struct {
	FilterField FilterField
	Valid       bool // Valid is true if FilterField is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFilterField) Scan(value interface{}) error {
	if value == nil {
		ns.FilterField, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FilterField.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFilterField) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FilterField), nil
}

type FilterOperator string

const (
	FilterOperatorContains       FilterOperator = "contains"
	FilterOperatorDoesNotContain FilterOperator = "does_not_contain"
)

func (e *FilterOperator) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FilterOperator(s)
	case string:
		*e = FilterOperator(s)
	default:
		return fmt.Errorf("unsupported scan type for FilterOperator: %T", src)
	}
	return nil
}

type NullFilterOperator struct {
	FilterOperator FilterOperator
	Valid          bool // Valid is true if FilterOperator is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFilterOperator) Scan(value interface{}) error {
	if value == nil {
		ns.FilterOperator, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FilterOperator.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFilterOperator) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FilterOperator), nil
}

type Frequency string

const (
	FrequencyMonthly Frequency = "monthly"
	FrequencyWeekly  Frequency = "weekly"
	FrequencyDaily   Frequency = "daily"
)

func (e *Frequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Frequency(s)
	case string:
		*e = Frequency(s)
	default:
		return fmt.Errorf("unsupported scan type for Frequency: %T", src)
	}
	return nil
}

type NullFrequency struct {
	Frequency Frequency
	Valid     bool // Valid is true if Frequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.Frequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Frequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Frequency), nil
}

type ItemState string

const (
	ItemStateRead   ItemState = "read"
	ItemStateUnread ItemState = "unread"
)

func (e *ItemState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemState(s)
	case string:
		*e = ItemState(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemState: %T", src)
	}
	return nil
}

type NullItemState struct {
	ItemState ItemState
	Valid     bool // Valid is true if ItemState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemState) Scan(value interface{}) error {
	if value == nil {
		ns.ItemState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemState), nil
}

type AppUser struct {
	ID        string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Feed struct {
	ID              string
	Title           string
	Description     string
	Url             string
	LastRetrievedAt time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type FeedItem struct {
	ID          string
	FeedID      string
	Title       string
	Url         string
	PublishDate time.Time
	RetrievedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type FeedUrl struct {
	ID        string
	FeedID    string
	Url       string
	Source    FeedUrlSource
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Newsletter struct {
	ID           string
	Name         string
	Frequency    Frequency
	SendDay      int32
	SendHour     int32
	SendMinute   int32
	SendTimezone string
	LastSentAt   pgtype.Timestamptz
	NextSendTime time.Time
	UserID       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type NewsletterFeed struct {
	ID           string
	NewsletterID string
	FeedID       string
	UserID       string
	Alias        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type NewsletterFeedFilter struct {
	ID               string
	NewsletterFeedID string
	UserID           string
	Field            FilterField
	Operator         FilterOperator
	Pattern          string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type NewsletterFeedItemStatus struct {
	ID               string
	NewsletterFeedID string
	ItemID           string
	UserID           string
	State            ItemState
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type RefreshToken struct {
	ID        int64
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}
