// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Frequency string

const (
	FrequencyMonthly Frequency = "monthly"
	FrequencyWeekly  Frequency = "weekly"
	FrequencyDaily   Frequency = "daily"
)

func (e *Frequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Frequency(s)
	case string:
		*e = Frequency(s)
	default:
		return fmt.Errorf("unsupported scan type for Frequency: %T", src)
	}
	return nil
}

type NullFrequency struct {
	Frequency Frequency
	Valid     bool // Valid is true if Frequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.Frequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Frequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Frequency), nil
}

type AppUser struct {
	ID        string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Feed struct {
	ID              string
	NewsletterID    string
	Name            string
	Url             string
	LastRetrievedAt pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Newsletter struct {
	ID           string
	Name         string
	Frequency    Frequency
	SendDay      int32
	SendHour     int32
	SendMinute   int32
	SendTimezone string
	LastSentAt   pgtype.Timestamptz
	NextSendTime time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       string
}

type RefreshToken struct {
	ID        int64
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}
