// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Frequency string

const (
	FrequencyMonthly Frequency = "monthly"
	FrequencyWeekly  Frequency = "weekly"
	FrequencyDaily   Frequency = "daily"
)

func (e *Frequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Frequency(s)
	case string:
		*e = Frequency(s)
	default:
		return fmt.Errorf("unsupported scan type for Frequency: %T", src)
	}
	return nil
}

type NullFrequency struct {
	Frequency Frequency
	Valid     bool // Valid is true if Frequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.Frequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Frequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Frequency), nil
}

type Newsletter struct {
	ID         pgtype.UUID
	Name       string
	Frequency  Frequency
	SendDay    pgtype.Int4
	SendHour   int32
	SendMinute int32
	LastSentAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
