// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: newsletters.sql

package db

import (
	"context"
)

const createNewsletter = `-- name: CreateNewsletter :exec
INSERT INTO newsletter (name, frequency, send_day, send_hour, send_minute)
VALUES ($1, $2, $3, $4, $5)
`

type CreateNewsletterParams struct {
	Name       string
	Frequency  Frequency
	SendDay    int32
	SendHour   int32
	SendMinute int32
}

func (q *Queries) CreateNewsletter(ctx context.Context, arg CreateNewsletterParams) error {
	_, err := q.db.Exec(ctx, createNewsletter,
		arg.Name,
		arg.Frequency,
		arg.SendDay,
		arg.SendHour,
		arg.SendMinute,
	)
	return err
}

const deleteNewsletter = `-- name: DeleteNewsletter :exec
DELETE FROM newsletter WHERE id = $1
`

func (q *Queries) DeleteNewsletter(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNewsletter, id)
	return err
}

const doesNewsletterExist = `-- name: DoesNewsletterExist :one
SELECT EXISTS(SELECT 1 FROM newsletter WHERE id = $1)
`

func (q *Queries) DoesNewsletterExist(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, doesNewsletterExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getNewsletter = `-- name: GetNewsletter :one
SELECT id, name, frequency, send_day, send_hour, send_minute, last_sent_at, created_at, updated_at FROM newsletter
WHERE id = $1
`

func (q *Queries) GetNewsletter(ctx context.Context, id string) (Newsletter, error) {
	row := q.db.QueryRow(ctx, getNewsletter, id)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Frequency,
		&i.SendDay,
		&i.SendHour,
		&i.SendMinute,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNewsletters = `-- name: ListNewsletters :many
SELECT id, name, frequency, send_day, send_hour, send_minute, last_sent_at, created_at, updated_at FROM newsletter
ORDER BY created_at DESC
`

func (q *Queries) ListNewsletters(ctx context.Context) ([]Newsletter, error) {
	rows, err := q.db.Query(ctx, listNewsletters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Newsletter
	for rows.Next() {
		var i Newsletter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Frequency,
			&i.SendDay,
			&i.SendHour,
			&i.SendMinute,
			&i.LastSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNewsletter = `-- name: UpdateNewsletter :exec
UPDATE newsletter SET 
    name = $1,
    frequency = $2,
    send_day = $3,
    send_hour = $4,
    send_minute = $5,
    updated_at = NOW()
WHERE id = $6
`

type UpdateNewsletterParams struct {
	Name       string
	Frequency  Frequency
	SendDay    int32
	SendHour   int32
	SendMinute int32
	ID         string
}

func (q *Queries) UpdateNewsletter(ctx context.Context, arg UpdateNewsletterParams) error {
	_, err := q.db.Exec(ctx, updateNewsletter,
		arg.Name,
		arg.Frequency,
		arg.SendDay,
		arg.SendHour,
		arg.SendMinute,
		arg.ID,
	)
	return err
}
