// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (email, password) VALUES ($1, $2) RETURNING id
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var id string
	err := row.Scan(&id)
	return id, err
}

const doesUserWithEmailExist = `-- name: DoesUserWithEmailExist :one
SELECT EXISTS(SELECT 1 FROM app_user WHERE email = $1)
`

func (q *Queries) DoesUserWithEmailExist(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, doesUserWithEmailExist, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at, updated_at FROM app_user WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
