/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewslettersRouteImport } from './routes/newsletters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnsubscribeIndexRouteImport } from './routes/unsubscribe/index'
import { Route as NewslettersIndexRouteImport } from './routes/newsletters.index'
import { Route as NewslettersNewsletterIdRouteImport } from './routes/newsletters/$newsletterId'
import { Route as NewslettersNewsletterIdIndexRouteImport } from './routes/newsletters/$newsletterId/index'
import { Route as NewslettersNewsletterIdFeedsFeedIdRouteImport } from './routes/newsletters/$newsletterId/feeds/$feedId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersRoute = NewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeIndexRoute = UnsubscribeIndexRouteImport.update({
  id: '/unsubscribe/',
  path: '/unsubscribe/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersIndexRoute = NewslettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewslettersRoute,
} as any)
const NewslettersNewsletterIdRoute = NewslettersNewsletterIdRouteImport.update({
  id: '/$newsletterId',
  path: '/$newsletterId',
  getParentRoute: () => NewslettersRoute,
} as any)
const NewslettersNewsletterIdIndexRoute =
  NewslettersNewsletterIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NewslettersNewsletterIdRoute,
  } as any)
const NewslettersNewsletterIdFeedsFeedIdRoute =
  NewslettersNewsletterIdFeedsFeedIdRouteImport.update({
    id: '/feeds/$feedId',
    path: '/feeds/$feedId',
    getParentRoute: () => NewslettersNewsletterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newsletters': typeof NewslettersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/newsletters/$newsletterId': typeof NewslettersNewsletterIdRouteWithChildren
  '/newsletters/': typeof NewslettersIndexRoute
  '/unsubscribe/': typeof UnsubscribeIndexRoute
  '/newsletters/$newsletterId/': typeof NewslettersNewsletterIdIndexRoute
  '/newsletters/$newsletterId/feeds/$feedId': typeof NewslettersNewsletterIdFeedsFeedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/newsletters': typeof NewslettersIndexRoute
  '/unsubscribe': typeof UnsubscribeIndexRoute
  '/newsletters/$newsletterId': typeof NewslettersNewsletterIdIndexRoute
  '/newsletters/$newsletterId/feeds/$feedId': typeof NewslettersNewsletterIdFeedsFeedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newsletters': typeof NewslettersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/newsletters/$newsletterId': typeof NewslettersNewsletterIdRouteWithChildren
  '/newsletters/': typeof NewslettersIndexRoute
  '/unsubscribe/': typeof UnsubscribeIndexRoute
  '/newsletters/$newsletterId/': typeof NewslettersNewsletterIdIndexRoute
  '/newsletters/$newsletterId/feeds/$feedId': typeof NewslettersNewsletterIdFeedsFeedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/newsletters'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/newsletters/$newsletterId'
    | '/newsletters/'
    | '/unsubscribe/'
    | '/newsletters/$newsletterId/'
    | '/newsletters/$newsletterId/feeds/$feedId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/newsletters'
    | '/unsubscribe'
    | '/newsletters/$newsletterId'
    | '/newsletters/$newsletterId/feeds/$feedId'
  id:
    | '__root__'
    | '/'
    | '/newsletters'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/newsletters/$newsletterId'
    | '/newsletters/'
    | '/unsubscribe/'
    | '/newsletters/$newsletterId/'
    | '/newsletters/$newsletterId/feeds/$feedId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewslettersRoute: typeof NewslettersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  UnsubscribeIndexRoute: typeof UnsubscribeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters': {
      id: '/newsletters'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof NewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/': {
      id: '/unsubscribe/'
      path: '/unsubscribe'
      fullPath: '/unsubscribe/'
      preLoaderRoute: typeof UnsubscribeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/': {
      id: '/newsletters/'
      path: '/'
      fullPath: '/newsletters/'
      preLoaderRoute: typeof NewslettersIndexRouteImport
      parentRoute: typeof NewslettersRoute
    }
    '/newsletters/$newsletterId': {
      id: '/newsletters/$newsletterId'
      path: '/$newsletterId'
      fullPath: '/newsletters/$newsletterId'
      preLoaderRoute: typeof NewslettersNewsletterIdRouteImport
      parentRoute: typeof NewslettersRoute
    }
    '/newsletters/$newsletterId/': {
      id: '/newsletters/$newsletterId/'
      path: '/'
      fullPath: '/newsletters/$newsletterId/'
      preLoaderRoute: typeof NewslettersNewsletterIdIndexRouteImport
      parentRoute: typeof NewslettersNewsletterIdRoute
    }
    '/newsletters/$newsletterId/feeds/$feedId': {
      id: '/newsletters/$newsletterId/feeds/$feedId'
      path: '/feeds/$feedId'
      fullPath: '/newsletters/$newsletterId/feeds/$feedId'
      preLoaderRoute: typeof NewslettersNewsletterIdFeedsFeedIdRouteImport
      parentRoute: typeof NewslettersNewsletterIdRoute
    }
  }
}

interface NewslettersNewsletterIdRouteChildren {
  NewslettersNewsletterIdIndexRoute: typeof NewslettersNewsletterIdIndexRoute
  NewslettersNewsletterIdFeedsFeedIdRoute: typeof NewslettersNewsletterIdFeedsFeedIdRoute
}

const NewslettersNewsletterIdRouteChildren: NewslettersNewsletterIdRouteChildren =
  {
    NewslettersNewsletterIdIndexRoute: NewslettersNewsletterIdIndexRoute,
    NewslettersNewsletterIdFeedsFeedIdRoute:
      NewslettersNewsletterIdFeedsFeedIdRoute,
  }

const NewslettersNewsletterIdRouteWithChildren =
  NewslettersNewsletterIdRoute._addFileChildren(
    NewslettersNewsletterIdRouteChildren,
  )

interface NewslettersRouteChildren {
  NewslettersNewsletterIdRoute: typeof NewslettersNewsletterIdRouteWithChildren
  NewslettersIndexRoute: typeof NewslettersIndexRoute
}

const NewslettersRouteChildren: NewslettersRouteChildren = {
  NewslettersNewsletterIdRoute: NewslettersNewsletterIdRouteWithChildren,
  NewslettersIndexRoute: NewslettersIndexRoute,
}

const NewslettersRouteWithChildren = NewslettersRoute._addFileChildren(
  NewslettersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewslettersRoute: NewslettersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  UnsubscribeIndexRoute: UnsubscribeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
